export const people = [
    { id: '1', firstname: 'Sabrina', lastname: 'Ouhaddad', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Para-Médical', 'Bernafon', 'Paris', 'Grande Entreprise', 'Client', 'Commercial', 'Assistante Commerciale'] },
    { id: '2', firstname: 'Adeline', lastname: 'Portalez', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon'] },
    { id: '3', firstname: 'Carine', lastname: 'Munoz', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '4', firstname: 'Sara', lastname: 'Gregori', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Incubateur', 'Coaching'] },
    { id: '5', firstname: 'Eric', lastname: 'Micheau', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Grande Entreprise', 'Prospect', 'Editeur de logiciel', 'Maintenance', 'Cible prioritaire', 'Directeur', 'Tourisme', 'ACTEM\'otel'] },
    { id: '6', firstname: 'Alain', lastname: 'Guitet', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '7', firstname: 'Caroline', lastname: 'Boyenval', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Directrice commerciale', 'Client', 'Editeur de logiciel', 'Qiiro'] },
    { id: '8', firstname: 'Dominique', lastname: 'Saettel', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Prospection', 'Nice'] },
    { id: '9', firstname: 'Djessy', lastname: 'Denuit', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Coaching', 'Stratégie d\'Entreprise', 'Paris', 'Client', 'Septeo', 'Editeur de logiciel'] },
    { id: '10', firstname: 'Thomas', lastname: 'Bertrand', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Entrepreneur', 'Stratégie d\'Entreprise', 'Distribution Automatique', 'PME'] },
    { id: '11', firstname: 'Yves', lastname: 'Berard', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Directrice commerciale', 'Para-Médical', 'Bernafon', 'Paris', 'Grande Entreprise', 'Client'] },
    { id: '12', firstname: 'Marc', lastname: 'Laborie', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'KAM', 'Editeur de logiciel'] },
    { id: '13', firstname: 'Laurence', lastname: 'Villié', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Directrice commerciale', 'Grande Entreprise', 'Client', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon'] },
    { id: '14', firstname: 'Aurore', lastname: 'Cucumel', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '15', firstname: 'Mary', lastname: 'Barth', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon'] },
    { id: '16', firstname: 'Sanae', lastname: 'El Harrak', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '17', firstname: 'Catherine', lastname: 'Marziano', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon'] },
    { id: '18', firstname: 'Audrey', lastname: 'Berger', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Assistante Commerciale', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '19', firstname: 'Anaëlle', lastname: 'De Miguel', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '20', firstname: 'Tony', lastname: 'Grippon', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Stratégie d\'Entreprise', 'Growth', 'Directrice commerciale', 'Grande Entreprise', 'Client', 'Septeo', 'Septeo Hospitality', 'KAM', 'Editeur de logiciel', 'Prospection', 'Tourisme'] },
    { id: '21', firstname: 'Manon', lastname: 'Lyonnet', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Septeo', 'Editeur de logiciel', 'RRH', 'Cible prioritaire', 'Responsable Formation'] },
    { id: '22', firstname: 'Anouar', lastname: 'Lajmi', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Grande Entreprise', 'Commercial', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Septeo Solution Avocat'] },
    { id: '23', firstname: 'Shirley', lastname: 'Martinez', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Commercial', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Septeo Proptech', 'Mougin'] },
    { id: '24', firstname: 'Damien', lastname: 'Jean', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Marseille', 'Septeo', 'KAM', 'Editeur de logiciel', 'Septeo Ingeneo'] },
    { id: '25', firstname: 'Nathalie', lastname: 'Laurent', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Client', 'Office Manager', 'Ovea', 'IT'] },
    { id: '26', firstname: 'Benjamin', lastname: 'Bernabeu', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Directrice commerciale', 'Client', 'KAM', 'Prospection', 'Ovea', 'IT'] },
    { id: '27', firstname: 'Roland', lastname: 'Berne', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Directrice commerciale', 'Client', 'Marseille', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Septeo Ingeneo'] },
    { id: '28', firstname: 'Djamel', lastname: 'Kalai', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Client', 'Marseille', 'Commercial', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Septeo Ingeneo'] },
    { id: '29', firstname: 'Samantha', lastname: 'Serpe', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Client', 'Marseille', 'Commercial', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Septeo Ingeneo'] },
    { id: '30', firstname: 'Jean-Pierre', lastname: 'Sanchez', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Directrice commerciale', 'Grande Entreprise', 'Client', 'Copain', 'Septeo', 'Septeo Hospitality', 'KAM', 'Editeur de logiciel'] },
    { id: '31', firstname: 'Marion', lastname: 'Lechiguero', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Septeo', 'Editeur de logiciel', 'Responsable Formation'] },
    { id: '32', firstname: 'Dan', lastname: 'Kohn', solicitation_count: 3, last_solicitation_date: '2025-09-25', tags: ['Paris', 'Grande Entreprise', 'Client', 'Septeo', 'Editeur de logiciel', 'IT', 'Prospective'] },
    { id: '33', firstname: 'Anne-Laure', lastname: 'Coste', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Coaching', 'Directrice commerciale', 'Grande Entreprise', 'Client', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon', 'Prospection'] },
    { id: '34', firstname: 'Emilien', lastname: 'Guigue', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'GED'] },
    { id: '35', firstname: 'Michael', lastname: 'Gaudet', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Entrepreneur', 'AMOA', 'TPE'] },
    { id: '36', firstname: 'Laura', lastname: 'Krenn', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Perpignan', 'Incubateur', 'Responsable de secteur'] },
    { id: '37', firstname: 'Kim', lastname: 'Garrick', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Perpignan', 'Hardware'] },
    { id: '38', firstname: 'Axel', lastname: 'Oliveri', solicitation_count: 2, last_solicitation_date: '2025-08-22', tags: ['Perpignan', 'Incubateur', 'Coaching'] },
    { id: '39', firstname: 'Regis', lastname: 'Baclet', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'TPE', 'Perpignan', 'Expert-Comptable', 'Stratégie d\'Entreprise'] },
    { id: '40', firstname: 'Ghyslain', lastname: 'Morvan', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Entrepreneur', 'Traiteur', 'Growth'] },
    { id: '41', firstname: 'Laurent', lastname: 'Porteil', solicitation_count: 2, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Biarritz'] },
    { id: '42', firstname: 'Thomas', lastname: 'Milhem', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Para-Médical', 'Bernafon', 'Grande Entreprise', 'Client', 'Commercial'] },
    { id: '43', firstname: 'Valentin', lastname: 'Crabe', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Para-Médical', 'Bernafon', 'Grande Entreprise', 'Client', 'Commercial', 'Lille'] },
    { id: '44', firstname: 'Fiona', lastname: 'Heuvelin', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Para-Médical', 'Bernafon', 'Grande Entreprise', 'Client', 'Marseille', 'Commercial'] },
    { id: '45', firstname: 'Benoit', lastname: 'Arnaudin', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Directrice commerciale', 'Para-Médical', 'Bernafon', 'Grande Entreprise', 'Client'] },
    { id: '46', firstname: 'Anthony', lastname: 'Klee', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Biarritz', 'Équipement de l\'habitat', 'Para-Médical', 'Strasbourg', 'Bernafon'] },
    { id: '47', firstname: 'Céline', lastname: 'Barascud', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Retail', 'Équipement de l\'habitat', 'Directrice commerciale', 'Barascud'] },
    { id: '48', firstname: 'Laure', lastname: 'Barascud', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['PME', 'Retail', 'Équipement de l\'habitat', 'Barascud', 'Responsable service technique', 'Vendre'] },
    { id: '49', firstname: 'Antoine', lastname: 'Cavalier', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Retail', 'Équipement de l\'habitat', 'Barascud'] },
    { id: '50', firstname: 'Anthony', lastname: 'Reutenauer', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Retail', 'Équipement de l\'habitat', 'Barascud'] },
    { id: '51', firstname: 'Bruno', lastname: 'Barascud', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Entrepreneur', 'PME', 'Retail', 'Équipement de l\'habitat', 'Barascud'] },
    { id: '52', firstname: 'Helena', lastname: 'Palazzo', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Stratégie d\'Entreprise', 'PME', 'Directrice commerciale', 'Prospect', 'Editeur de logiciel', 'ESII'] },
    { id: '53', firstname: 'Lucie', lastname: 'Chareyre', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Pas lié', 'Santé', 'Chargé de communication', 'Dedienne Santé'] },
    { id: '54', firstname: 'Julien', lastname: 'Cros', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Commercial', 'Pas lié', 'Santé', 'Dedienne Santé'] },
    { id: '55', firstname: 'Ludovic', lastname: 'Toledo', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Pas lié', 'Santé', 'Dedienne Santé', 'Cible prioritaire', 'P&DG'] },
    { id: '56', firstname: 'Patrick', lastname: 'Brager', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Pas lié', 'Santé', 'Dedienne Santé', 'Cible prioritaire', 'Directeur'] },
    { id: '57', firstname: 'Matthieu', lastname: 'Fallet', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Pas lié', 'Santé', 'Dedienne Santé', 'Achats'] },
    { id: '58', firstname: 'Julien', lastname: 'Augoyard', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Pas lié', 'Santé', 'Dedienne Santé', 'Marketing'] },
    { id: '59', firstname: 'Gael', lastname: 'Bill', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Entrepreneur', 'Client', 'Editeur de logiciel', 'Qiiro'] },
    { id: '60', firstname: 'Rafaelle', lastname: 'Cromieres', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Client', 'Editeur de logiciel', 'Qiiro', 'RRH'] },
    { id: '61', firstname: 'Yannick', lastname: 'Gilly', solicitation_count: 1, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Entrepreneur', 'AMOA', 'Stratégie d\'Entreprise', 'PME', 'Copain', 'Editeur de logiciel', 'P&DG'] },
    { id: '62', firstname: 'Philippe', lastname: 'Bruté de Remur', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Montpellier', 'Directrice commerciale', 'Grande Entreprise', 'Client', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '63', firstname: 'Gaël', lastname: 'Philippe', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Entrepreneur', 'AMOA', 'Directrice commerciale', 'IT', 'DataSulting'] },
    { id: '64', firstname: 'Olivier', lastname: 'Lacombe', solicitation_count: 2, last_solicitation_date: '2025-08-25', tags: ['Montpellier', 'Entrepreneur', 'AMOA', 'TPE', 'Client', 'Copain', 'Editeur de logiciel', 'IT'] },
    { id: '65', firstname: 'Ambre', lastname: 'Verguin', solicitation_count: 2, last_solicitation_date: '2025-09-25', tags: ['Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Lyon'] },
    { id: '66', firstname: 'Abdelilah', lastname: 'Sanif', solicitation_count: 0, last_solicitation_date: null, tags: ['Entrepreneur', 'AMOA', 'Hardware', 'PME', 'Prospect', 'Maintenance', 'P&DG', 'Directeur', 'IT', 'DevCSI'] },
    { id: '67', firstname: 'Danny', lastname: 'Saliba', solicitation_count: 0, last_solicitation_date: null, tags: ['PME', 'Prospect', 'Commercial', 'Pas lié', 'Santé', 'Dedienne Santé', 'Grenoble'] },
    { id: '68', firstname: 'Loïc', lastname: 'Renault-Renaud', solicitation_count: 0, last_solicitation_date: null, tags: ['PME', 'Prospect', 'Commercial', 'Pas lié', 'Santé', 'Dedienne Santé', 'Bretagne'] },
    { id: '69', firstname: 'Morgan', lastname: 'Spruytte', solicitation_count: 0, last_solicitation_date: null, tags: ['PME', 'Prospect', 'Commercial', 'Lyon', 'Pas lié', 'Santé', 'Dedienne Santé', 'Cible prioritaire'] },
    { id: '70', firstname: 'Sylvie', lastname: 'Naudin', solicitation_count: 0, last_solicitation_date: null, tags: ['PME', 'Prospect', 'Commercial', 'Pas lié', 'Santé', 'Dedienne Santé', 'Auvergne'] },
    { id: '71', firstname: 'Romane', lastname: 'Toledo', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'PME', 'Prospect', 'Commercial', 'Pas lié', 'Santé', 'Dedienne Santé', 'Cible prioritaire'] },
    { id: '72', firstname: 'Afef', lastname: 'Louardi', solicitation_count: 1, last_solicitation_date: '2025-08-22', tags: ['Montpellier', 'Client', 'Commercial', 'Ovea', 'IT'] },
    { id: '73', firstname: 'Stéphane', lastname: 'Perriat', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '74', firstname: 'Frédéric', lastname: 'Frouin', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '75', firstname: 'Marc', lastname: 'Tavernier', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '76', firstname: 'Philippe', lastname: 'Crespin', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '77', firstname: 'Sophie', lastname: 'Sizeun', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '78', firstname: 'Matthieu', lastname: 'Monferran', solicitation_count: 1, last_solicitation_date: '2025-09-02', tags: ['Ex-Booster Academy', 'Commercial'] },
    { id: '79', firstname: 'Sandrine', lastname: 'Brunner', solicitation_count: 0, last_solicitation_date: null, tags: ['Montpellier', 'Grande Entreprise', 'Prospect', 'Copain', 'Commercial', 'Septeo', 'Editeur de logiciel', 'Prospection', 'Cible prioritaire', 'Septeo Solution Avocat'] },
    { id: '80', firstname: 'Mouad', lastname: 'Serraj', solicitation_count: 0, last_solicitation_date: null, tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Commercial', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel'] },
    { id: '81', firstname: 'Anaïs', lastname: 'Vidal', solicitation_count: 0, last_solicitation_date: null, tags: ['Montpellier', 'Grande Entreprise', 'Client', 'Septeo', 'Septeo Hospitality', 'Editeur de logiciel', 'Grenoble'] },
    { id: '82', firstname: 'Franck', lastname: 'Albini', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'Commercial', 'SOA People', 'Maintenance', 'Prospection'] },
    { id: '83', firstname: 'Galien', lastname: 'Sénécot', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '84', firstname: 'Raphaël', lastname: 'Lacan', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '85', firstname: 'Christophe', lastname: 'Dechavanne', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '86', firstname: 'David', lastname: 'Sanaphonh', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '87', firstname: 'Mariya', lastname: 'Shevchuk', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '88', firstname: 'Christoph', lastname: 'Labedzki', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
    { id: '89', firstname: 'Thibault', lastname: 'Meyer', solicitation_count: 0, last_solicitation_date: null, tags: ['AMOA', 'Grande Entreprise', 'Client', 'SOA People', 'Consultant'] },
];

export const tags = [
    { id: 1, name: 'Montpellier', category: 'Ville', is_priority: false },
    { id: 2, name: 'GED', category: 'Compétences', is_priority: false },
    { id: 3, name: 'Entrepreneur', category: 'Poste', is_priority: false },
    { id: 4, name: 'AMOA', category: 'Secteur d\'activité', is_priority: false },
    { id: 5, name: 'TPE', category: 'Taille d\'entreprise', is_priority: false },
    { id: 6, name: 'Perpignan', category: 'Ville', is_priority: false },
    { id: 7, name: 'Hardware', category: 'Secteur d\'activité', is_priority: false },
    { id: 8, name: 'Incubateur', category: 'Secteur d\'activité', is_priority: false },
    { id: 9, name: 'Responsable de secteur', category: 'Poste', is_priority: false },
    { id: 10, name: 'Coaching', category: 'Compétences', is_priority: false },
    { id: 11, name: 'Expert-Comptable', category: 'Secteur d\'activité', is_priority: false },
    { id: 12, name: 'Stratégie d\'Entreprise', category: 'Compétences', is_priority: false },
    { id: 13, name: 'Traiteur', category: 'Secteur d\'activité', is_priority: false },
    { id: 14, name: 'Growth', category: 'Compétences', is_priority: false },
    { id: 15, name: 'Distribution Automatique', category: 'Secteur d\'activité', is_priority: false },
    { id: 16, name: 'PME', category: 'Taille d\'entreprise', is_priority: false },
    { id: 17, name: 'Ex-Booster Academy', category: 'Entreprise', is_priority: false },
    { id: 18, name: 'Biarritz', category: 'Ville', is_priority: false },
    { id: 20, name: 'LSD', category: 'Entreprise', is_priority: false },
    { id: 22, name: 'Retail', category: 'Secteur d\'activité', is_priority: false },
    { id: 23, name: 'Équipement de l\'habitat', category: 'Secteur d\'activité', is_priority: false },
    { id: 24, name: 'Directrice commerciale', category: 'Poste', is_priority: false },
    { id: 25, name: 'Barascud', category: 'Entreprise', is_priority: false },
    { id: 26, name: 'Responsable service technique', category: 'Poste', is_priority: false },
    { id: 27, name: 'Vendre', category: 'Ville', is_priority: false },
    { id: 28, name: 'Para-Médical', category: 'Secteur d\'activité', is_priority: false },
    { id: 29, name: 'Strasbourg', category: 'Ville', is_priority: false },
    { id: 30, name: 'Bernafon', category: 'Entreprise', is_priority: false },
    { id: 31, name: 'Paris', category: 'Ville', is_priority: false },
    { id: 32, name: 'Grande Entreprise', category: 'Taille d\'entreprise', is_priority: false },
    { id: 33, name: 'Client', category: 'Type de relation', is_priority: false },
    { id: 34, name: 'Prospect', category: 'Type de relation', is_priority: false },
    { id: 35, name: 'Copain', category: 'Type de relation', is_priority: false },
    { id: 36, name: 'Marseille', category: 'Ville', is_priority: false },
    { id: 37, name: 'Commercial', category: 'Poste', is_priority: false },
    { id: 38, name: 'Lille', category: 'Ville', is_priority: false },
    { id: 39, name: 'Assistante Commerciale', category: 'Poste', is_priority: false },
    { id: 40, name: 'Septeo', category: 'Entreprise', is_priority: false },
    { id: 41, name: 'Septeo Hospitality', category: 'Entreprise', is_priority: false },
    { id: 42, name: 'KAM', category: 'Poste', is_priority: false },
    { id: 43, name: 'Editeur de logiciel', category: 'Secteur d\'activité', is_priority: false },
    { id: 44, name: 'Lyon', category: 'Ville', is_priority: false },
    { id: 45, name: 'SOA People', category: 'Entreprise', is_priority: false },
    { id: 46, name: 'Consultant', category: 'Poste', is_priority: false },
    { id: 47, name: 'Maintenance', category: 'Secteur d\'activité', is_priority: false },
    { id: 48, name: 'Prospection', category: 'Compétences', is_priority: false },
    { id: 49, name: 'Qiiro', category: 'Entreprise', is_priority: false },
    { id: 50, name: 'RRH', category: 'Poste', is_priority: false },
    { id: 51, name: 'Pas lié', category: 'Type de relation', is_priority: false },
    { id: 52, name: 'Santé', category: 'Secteur d\'activité', is_priority: false },
    { id: 53, name: 'Chargé de communication', category: 'Poste', is_priority: false },
    { id: 54, name: 'Dedienne Santé', category: 'Entreprise', is_priority: false },
    { id: 55, name: 'Cible prioritaire', category: 'Statut', is_priority: false },
    { id: 56, name: 'P&DG', category: 'Poste', is_priority: false },
    { id: 57, name: 'Directeur', category: 'Poste', is_priority: false },
    { id: 58, name: 'Achats', category: 'Poste', is_priority: false },
    { id: 59, name: 'Marketing', category: 'Poste', is_priority: false },
    { id: 60, name: 'Grenoble', category: 'Ville', is_priority: false },
    { id: 61, name: 'Bretagne', category: 'Ville', is_priority: false },
    { id: 62, name: 'Auvergne', category: 'Ville', is_priority: false },
    { id: 63, name: 'ESII', category: 'Entreprise', is_priority: false },
    { id: 64, name: 'Tourisme', category: 'Secteur d\'activité', is_priority: false },
    { id: 65, name: 'Responsable Formation', category: 'Poste', is_priority: false },
    { id: 66, name: 'Septeo Solution Avocat', category: 'Entreprise', is_priority: false },
    { id: 67, name: 'Septeo Proptech', category: 'Entreprise', is_priority: false },
    { id: 68, name: 'Mougin', category: 'Ville', is_priority: false },
    { id: 69, name: 'Septeo Ingeneo', category: 'Entreprise', is_priority: false },
    { id: 70, name: 'Office Manager', category: 'Poste', is_priority: false },
    { id: 71, name: 'Ovea', category: 'Entreprise', is_priority: false },
    { id: 72, name: 'IT', category: 'Secteur d\'activité', is_priority: false },
    { id: 74, name: 'Prospective', category: 'Compétences', is_priority: false },
    { id: 75, name: 'Nice', category: 'Ville', is_priority: false },
    { id: 77, name: 'ACTEM\'otel', category: 'Entreprise', is_priority: false },
    { id: 78, name: 'DevCSI', category: 'Entreprise', is_priority: false },
    { id: 79, name: 'DataSulting', category: 'Entreprise', is_priority: false },
];
